language: python
python:
  - "2.6"
  - "2.7"
before_install:
  - sudo apt-get install liblapack-dev gfortran libblas-dev
  - sudo apt-get install samtools
install:
  - travis_wait pip install scipy
  - travis_wait pip install pysam
  - pip install .
script:
  - python -m unittest discover misopy